- name: Run database container
  community.docker.docker_container:
    name: my-database
    image: safaeberr/project-docker-initdb:latest
    state: started
    restart_policy: always
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - name: app-network
